version: '3.9'
services:
  tyk-dashboard:
    environment:
      - TYK_DB_STORAGE_MAIN_TYPE=postgres
      - TYK_DB_STORAGE_MAIN_CONNECTIONSTRING=user=postgres password=topsecretpassword host=tyk-postgres port=5432 database=tyk_analytics
    depends_on:
      tyk-postgres:
        condition: service_healthy

  tyk-pump:
    env_file:
      - ./confs/pump.postgres.env
    depends_on:
      tyk-postgres:
        condition: service_healthy
      
  tyk-mongo:
    entrypoint: ["echo", "Docker Mongo service disabled. Using Postgres service instead.", ""]
    command: []
