version: '3.9'
services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:v4.2.3
    container_name: tyk-dashboard
    environment:
      - TYK_DB_LICENSEKEY=
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGxvd2VkX25vZGVzIjoiZmQ3ZjdkMGEtNTgzOC00M2EzLTUwM2MtZGQ2NDRmMjNkODc2LDI2NmUyMWRlLTFjZjctNGIxNS02YzFhLTJlODQxNDI3NWU2ZSw2NWY5NTI3My0yZDAzLTRiM2UtNTA4Zi0xZjZhMWE5NmU2NjUsZGZlZDNmZjgtNzU5NC00MDEyLTViMWItMTRkZmUwNDk4ZjUwLDNkNTNhMDIwLTA5MzQtNDhhYy02NGQ3LWFiODZlN2VjYzEzMyIsImV4cCI6MTY2OTM1MDkyOSwiaWF0IjoxNjY4MTQxMzI5LCJvd25lciI6IjYzNmRkMTExOGRiZTY2MDAwMWRlNTVmNCIsInNjb3BlIjoidHJhY2sscmJhYyxtdWx0aV90ZWFtLHVkZyxncmFwaCxmZWRlcmF0aW9uIiwidiI6IjIifQ.zDe0JfRYvx5SBoW3VaBXntOiVP0oEIx91KzO24FPP7PEQZxBIC7_EyWsogJTq-EVW13YgXvwBF2dV781XX2-p4U38BgggoA0gx5C1OFX3LblHsJPw3uFKKRXQCAawhmHm_f9DsAV1wA0Az7OlXp3UzbQO0PjlqfqWrLV0mToo_Gz8wI_-b62FR6NVXs9Sp-4JA7wRyCLf1KUAuHMhKCbhlRCbVALXCPUKWlDk4YuPnFXD1kCpqS7JCA1SBPOUL5Z-8oaYiQbatjpkxAWWzhnL77deQioD6ib9nJ0jG6MVlcy6FxhiS_DeJXMIN93GmpOXlMBMcsdC7iaAjl-OAUChQ
      - TYK_DB_STORAGE_MAIN_TYPE=postgres
      - TYK_DB_STORAGE_MAIN_CONNECTIONSTRING=mongodb://tyk-mongo:27017/tyk_analytics
    ports:
      - "3000:3000"
    env_file:
      - ./confs/tyk_analytics.env
    networks:
      - tyk

  tyk-gateway:
    image: tykio/tyk-gateway:v4.2.3
    container_name: tyk-gateway
    ports:
      - "8080:8080"
    env_file:
      - ./confs/tyk.env
    networks:
      - tyk

  tyk-pump:
    image: tykio/tyk-pump-docker-pub:v1.5.1
    container_name: tyk-pump
    env_file:
      - ./confs/pump.env
      - ./confs/pump.mongo.env
    networks:
      - tyk

 
