version: '3.9'
services:
  tyk-dashboard-region-a:
    image: tykio/tyk-dashboard:v4.1.0-rc1
    container_name: tyk-dashboard-region-a
    environment:
      - TYK_DB_LISTENPORT=3000
      - TYK_DB_LICENSEKEY=${TYK_DB_LICENSEKEY_A}
      - TYK_DB_TYKAPI_HOST=http://tyk-gateway-region-a
      - TYK_DB_TYKAPI_PORT=8080
      - TYK_DB_HOSTCONFIG_GATEWAYHOSTNAME=localhost:8080
      - TYK_DB_STORAGE_MAIN_TYPE=postgres
      - TYK_DB_STORAGE_MAIN_CONNECTIONSTRING=user=default password=topsecretpassword host=tyk-postgres port=5432 database=tyk_analytics
      - TYK_DB_REDISADDRS=tyk-redis-cluster-region-a-master-0:6379,tyk-redis-cluster-region-a-master-1:6379,tyk-redis-cluster-region-b-master-2:6379,tyk-redis-cluster-region-b-master-3:6379,tyk-redis-cluster-region-a-replica-0:6379,tyk-redis-cluster-region-a-replica-1:6379,tyk-redis-cluster-region-b-replica-2:6379,tyk-redis-cluster-region-b-replica-3
      - TYK_DB_ENABLECLUSTER=true
    ports:
      - "3000:3000"
    env_file:
      - ../confs/tyk_analytics.env
    networks:
      - tyk
    restart: always

  tyk-gateway-region-a:
    image: tykio/tyk-gateway:v4.1.0-rc10
    container_name: tyk-gateway-region-a
    ports:
      - "8080:8080"
    env_file:
      - ../confs/tyk.env
    environment:
      - TYK_GW_LISTENPORT=8080
      - TYK_GW_POLICIES_POLICYCONNECTIONSTRING=http://tyk-dashboard-region-a:3000
      - TYK_GW_DBAPPCONFOPTIONS_CONNECTIONSTRING=http://tyk-dashboard-region-a:3000
      - TYK_GW_STORAGE_ADDRS=tyk-redis-cluster-region-a-master-0:6379,tyk-redis-cluster-region-a-master-1:6379,tyk-redis-cluster-region-b-master-2:6379,tyk-redis-cluster-region-b-master-3:6379,tyk-redis-cluster-region-a-replica-0:6379,tyk-redis-cluster-region-a-replica-1:6379,tyk-redis-cluster-region-b-replica-2:6379,tyk-redis-cluster-region-b-replica-3
      - TYK_GW_STORAGE_ENABLECLUSTER=true
    networks:
      - tyk

  tyk-mdcb-region-a:
    image: tykio/tyk-mdcb-docker:v1.9.0-rc2
    container_name: tyk-mdcb-region-a
    environment:
      - TYK_MDCB_LISTENPORT=9090
      - TYK_MDCB_HEALTHCHECKPORT=8181
      - TYK_MDCB_LICENSE=${TYK_MDCB_LICENSE_A}
      - TYK_MDCB_HASHKEYS=true
      - TYK_MDCB_FORWARDANALYTICSTOPUMP=true
      - TYK_MDCB_SYNCWORKER_ENABLED=true
      - TYK_MDCB_SYNCWORKER_HASHKEYS=true
      - TYK_MDCB_ANALYTICSCONFIG_TYPE=postgres
      - TYK_MDCB_ANALYTICSCONFIG_CONNECTIONSTRING=user=default password=topsecretpassword host=tyk-postgres port=5432 database=tyk_analytics
      - TYK_MDCB_STORAGE_ADDRS=tyk-redis-cluster-region-a-master-0:6379,tyk-redis-cluster-region-a-master-1:6379,tyk-redis-cluster-region-b-master-2:6379,tyk-redis-cluster-region-b-master-3:6379,tyk-redis-cluster-region-a-replica-0:6379,tyk-redis-cluster-region-a-replica-1:6379,tyk-redis-cluster-region-b-replica-2:6379,tyk-redis-cluster-region-b-replica-3
      - TYK_MDCB_STORAGE_ENABLECLUSTER=true
    ports:
      - "9090:9090"
      - "8181:8181"
    networks:
      - tyk
    restart: always

networks:
  tyk:
    external: true
