version: '3.9'
services:
  tyk-redis-region-a-hybrid-0:
    image: redis
    container_name: tyk-redis-region-a-hybrid-0
    networks:
      - tyk

  tyk-gateway-region-a-hybrid-0:
    image: tykio/tyk-gateway:v4.1.0-rc10
    container_name: tyk-gateway-region-a-hybrid-0
    ports:
      - "8081:8081"
    env_file:
      - ../confs/tyk.env
    environment:
      - TYK_GW_LISTENPORT=8081
      - TYK_GW_POLICIES_POLICYSOURCE=rpc
      - TYK_GW_USEDBAPPCONFIGS=false
      - TYK_GW_STORAGE_ADDRS=tyk-redis-region-a-hybrid-0:6379
      - TYK_GW_ANALYTICSCONFIG_TYPE=rpc
      - TYK_GW_SLAVEOPTIONS_USERPC=true
      - TYK_GW_SLAVEOPTIONS_CONNECTIONSTRING=tyk-mdcb-region-a:9090
      - TYK_GW_SLAVEOPTIONS_RPCKEY=${TYK_GW_SLAVEOPTIONS_RPCKEY}
      - TYK_GW_SLAVEOPTIONS_APIKEY=${TYK_GW_SLAVEOPTIONS_APIKEY}
      - TYK_GW_SLAVEOPTIONS_GROUPID=region-a-hybrid-0
      - TYK_GW_AUTHOVERRIDE_SESSIONPROVIDER_STORAGEENGINE=rpc
    networks:
      - tyk

networks:
  tyk:
    external: true 
